---
- name: Install WP-CLI
  get_url: url={{ wp_cli_url }} dest={{ wp_cli_bin }} mode=0755

- name: Download WordPress
  command: wp core download
    --path={{ wp_root }}
    --locale={{ wp_lang }}
    --version={{ wp_version }}
    --allow-root
    creates={{ wp_root }}

- name: Fetch random salts for WordPress config
  command: curl http://api.wordpress.org/secret-key/1.1/salt/
  register: wp_salt

- name: Add WordPress config file
  template: src=wp-config.php dest=/srv/wordpress/

- name: Change ownership of WordPress installation
  file: path={{ wp_root }} owner=www-data group=www-data state=directory recurse=yes

- name: Change upload permissions
  file: path={{ wp_root }}/wp-content/uploads mode=775 state=directory recurse=yes

- name: Create WordPress database
  mysql_db: name={{ wp_db_name }} state=present

- name: Create WordPress database user
  mysql_user: name={{ wp_db_user }} password={{ wp_db_password }} priv={{ wp_db_name }}.*:ALL state=present

- name: Install WordPress tables
  command: wp core install
    --url={{ hostname }}
    --title="{{ site_name }}"
    --admin_user={{ wp_admin_user }}
    --admin_password={{ wp_admin_password }}
    --admin_email={{ wp_admin_email }}
    --allow-root
    chdir={{ wp_root }}
  notify: Reload Nginx

- name: Delete Hello Dolly plugin
  command: wp plugin delete hello --allow-root chdir={{ wp_root }}
  when: delete_hello_dolly

- name: Install WordPress plugins
  command: wp plugin install {{ item.name }} --version={{ item.version }} --activate --force --allow-root chdir={{ wp_root }}
  with_items: wp_plugins
  when: wp_plugins is defined

- name: Delete all content
  command: wp site empty --yes --allow-root chdir={{ wp_root }}
  when: delete_all_content

- include: db_import.yml
  when: wp_db_import|default(False)
